apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitter
  name: twitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      containers:
        - image: gcr.io/bootiful/twitter
          imagePullPolicy: Always
          name: twitter-container
          startupProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          envFrom:
            - secretRef:
                name: twitter-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: LANG
              value: "en_US.UTF-8"
#            - name: TWITTER_ENCRYPTION_SALT
#              valueFrom:
#                secretKeyRef:
#                  name: twitter-secrets
#                  key: TWITTER_ENCRYPTION_SALT
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"