apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitter-hub
  name: twitter-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-hub
  template:
    metadata:
      labels:
        app: twitter-hub
    spec:
      containers:
        - image: gcr.io/bootiful/twitter-hub
          imagePullPolicy: Always
          name: twitter-hub-container
          startupProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          readinessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/readiness

          livenessProbe:
            failureThreshold: 60
            periodSeconds: 60
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          envFrom:
            - secretRef:
                name: twitter-hub-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: LANG
              value: "en_US.UTF-8"
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"