apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    networking.gke.io/managed-certificates: "twitter-hub-certificate"
    kubernetes.io/ingress.global-static-ip-name: "content-hubs-twitter-hub-ip"
  name: twitter-hub-ingress
spec:
  defaultBackend:
    service:
      name: twitter-hub
      port:
        number: 80

